### ISSUE TITLE
Add Template for Pull Request

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/Marketplace#4]
The template must have the following parts:
- Title: Pull Request Overview
- Summary
- Changes Made
- Tests Results
- Next Steps

Use the following photo as an example:
<img width="833" alt="Screenshot 2024-10-29 at 11 36 24 AM" src="https://github.com/user-attachments/assets/b6c875ea-380d-4be9-9291-9ca3969b20ed">

**Comment by petersdt** [comment]
Is this issue still available? I would like to contribute to this ETA  3days

previous doc by me:
- [cairo book contribution](https://github.com/cairo-book/cairo-book/pull/788)

**Comment by Akshola00** [comment]
Can I jump on this task?

**Comment by martinvibes** [comment]
Could I try solving this?
Kindly assign

**Comment by CollinsC1O** [comment]
Can I be assigned to this?

**Comment by jedstroke** [comment]
Can I try solving this issue?

**Comment by MPSxDev** [comment]
I would love to take on this issue. I am a member of the Dojo Coding. I am immediately available. @jimenezz22

**Comment by DiegoB1911** [comment]
I'm a Full Stack Developer with two years of experience. I'm also a member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies. I'm enthusiastic about learning, and becoming a part of this project.
To address this issue, I would take the following steps:

1. Create the Template File:  
   I would create a new file named pull_request_template.md.

2. Define the Structure of the Template:  
   I will adjust the pull_request_template.md file to include the required sections.

3. Test the Template:  
   I would ensure that the template works by creating a new pull request in the repository and verifying that it automatically populates the description area, allowing contributors to fill in the necessary details.

**Comment by nov0ax** [comment]
Let me handle this issue!
I'd like to make my first contribution to this amazing project, I've been on an intesive road map with the help of Dojo Coding CR comunity

**Comment by derianrddev** [comment]
Hello, I’m Derian, a software engineer focused on full-stack web development, and I’m currently part of Dojo Coding. I’d like to work on this issue.

Here’s how I would solve the issue:

Create the .github folder in the root of the repository.
Add the template within that folder with the parts described in the issue.
Save and upload the file to the repository.
If I have any questions, I’ll ask in the Telegram group as soon as possible.
I’ll open a PR and wait for your feedback.
I’ll make the necessary changes according to the PR review.

**Comment by n3la88** [comment]
Hi team!
I’d like to work on this issue and contribute to the project. To approach it, I propose adding a checklist under the "Summary" section to help the team quickly identify if the change falls under [Bug fix, New feature, Breaking change, or Documentation update required post-merge]. This is just a proposal, and I’m excited to tackle the issue in a way that best aligns with the project’s structure and goals.

Looking forward to any guidance or feedback you might have!

**Comment by JosueBrenes** [comment]
Hi, I'm **Josué Brenes** and I'll be working on issue.
I'm Dojo Coding member.

I estimate this will take **1 day** to complete.

To resolve this, I would create a Markdown template file (pull_request_template.md) in the .github directory of the repository. This file would include the required sections in Markdown format, making it automatically available in each Pull Request.

```tsx

# Pull Request Overview

## 📝 Summary
- Closes #(issue)
- Brief description of the purpose of the Pull Request.

## 🔄 Changes Made
- List of code changes, specifying the modules or sections affected.

## 🧪 Tests Results
- Results of the tests executed.
  - Example: "Unit tests: 15/15 passed"
  - Example: "Integration tests: 10/10 passed"

## 🚀 Next Steps
- Pending actions or next steps if applicable (e.g., additional reviews or tests by other teams).
```

**Comment by akintewe** [comment]
I’d like to help with this. I am very familiar with the documentation architecture. Thank you so much. ETA <6 hrs

**Comment by Benjtalkshow** [comment]
I would love to work on this. I have implemented various Pull Request templates. My ETA is 24hrs.

**Comment by Kaminar-i** [comment]
I’d like to work on this

**Comment by bruhhgnik** [comment]
i'd love to work on this, im very enthusiastic about making PR templates, i love doing that on my free time

**Comment by sigmadawg** [comment]
im a newbie contributor, i'd be grateful if you'd give me the opportunity to work in this.

**Comment by jimenezz22** [comment]
assigned to you @nov0ax
